[target.thumbv7em-none-eabihf]

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# runner = "gdb-multiarch -q -x openocd.gdb"
runner = "probe-rs run --chip nRF52833_xxAA"

rustflags = [
    "-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "info"
DEFMT_RTT_BUFFER_SIZE = "1024"
